* Why do you want to work here
** I am excited for this opportunity because I feel that it will allow me
** to use my analytical and problem solving skills in a fast paced and challenging
** environment. I've seen on your profile that your encourage people to acquire 
** new, unique skills through learning platforms like pluralsite, so this fits in
** well with my personal motto. Which is if one is not learning, then one is regressing.

* Why Should we hire you.
** Technology is always evolving,this means that people have to be always learning
** new skills to keep up. My keeness to be continously learning and acquire new skills
** makes me a good  fit in a fast paced environment that requires people to be always
** on their toes, so to speak.
** Also the fact that I finished my Applied Mathematics and Computer Science
** in four years whilst holding down a fulltime job is testament to my work ethic.

* What are your strengths
** Analytical, This means that I always want to understand how certain patterns affect 
** one another. What is their outcome and do they fit the thesis being offered.
** 

* What are your Weaknesses
** Getting side tracked. In the process of learning new things, I often discover that there's
** more things I don't know and Immediately want to learn them as well before I am done with 
** what I set out to do. I now take note of the things I am unfamilliar with whilst in the process of 
** learning so that I can get back to them later when I am done learning what I originally set out to learn.

* Tell us about a time you had a conflict at work and how you reolved it?
** 